services:
  ollama:
    image: ollama/ollama
    restart: always
    container_name: ollama
    volumes:
      - "./ollama-volume:/root/.ollama"
    ports:
      - "11434:11434"
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    container_name: open-webui
    volumes:
      - "./open-webui:/app/backend/data"
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_URL=http://ollama:8080